type SingleMovie = {
  id: number;
  module: string;
  backdrop_path: string;
  poster_path: string;
  title: string;
  tagline: string;
  overview: string;
  release_date: string;
  runtime: number;
  budget: number;
  revenue: number;
  status: string;
  vote_average: number;
  vote_count: number;
  popularity: number;
  imdb_id: string;
  homepage?: string;
  genres?: { id: number; name: string; }[];
  production_companies?: { id: number; name: string; origin_country: string; }[];
  production_countries?: { iso_3166_1: string; name: string; }[];
  spoken_languages?: { iso_639_1: string; english_name: string; name: string; }[];
};
